
sudo: false
# addons:
#  apt:
#    packages:
#      - oracle-java8-installer

matrix:
    include:
    - os: linux
      language: java
      jdk:  oraclejdk8
      install: true
    - os: linux
      language: java
      jdk:  oraclejdk9
      install: true
    - os: linux
      language: java
      jdk:  openjdk11
    - os: linux
      language: java
      jdk:  openjdk-ea
    - os: linux
      language: java
      jdk:  openjdk12  
    allow_failures:
       - os: linux
         language: java
         jdk:  openjdk-ea
       - os: linux
         language: java
         jdk:  openjdk12  

before_script:
  - bash ./gradlew --version
  
script:
    - bash ./gradlew clean build test -S
    
#after_success:
#  - TERM=dumb ./gradlew test jacocoTestReport jacocoRootReport coveralls -S
